import Sneakers from "@/app/(tabs)/categories/sneakers";

export const Icons = {
  person: require("../assets/icons/solar_user-bold.png"),
  email: require("../assets/icons/fluent_mail-12-filled.png"),
  password: require("../assets/icons/mdi_password.png"),
  phone: require("../assets/icons/solar_phone-bold.png"),
  search: require("../assets/icons/search.png"),
  home: require("../assets/icons/home.png"),
  homeFocued: require("../assets/icons/homeFocused.png"),
  bookmark: require("../assets/icons/bookmark.png"),
  bookmarkFocued: require("../assets/icons/bookmarkFocused.png"),
  cart: require("../assets/icons/cart.png"),
  cartFocued: require("../assets/icons/cartFocused.png"),
  profile: require("../assets/icons/profile.png"),
  profileFocused: require("../assets/icons/profileFocused.png"),
  lens: require("../assets/icons/lens.png"),
  lensFocused: require("../assets/icons/lensFocused.png"),
  edit: require("../assets/icons/edit.png"),
  checked: require("../assets/icons/checked.png"),
  unchecked: require("../assets/icons/unchecked.png"),
  heart: require("../assets/icons/heart.png"),
};

export const Images = {
  banner: require("../assets/images/banner.png"),
  banner1: require("../assets/images/banner1.png"),
  avatar: require("../assets/images/avatar.png"),
  product: require("../assets/images/product.png"),
  products: require("../assets/images/products.png"),
  heels: require("../assets/images/heels.png"),
  cloudedLock: require("../assets/images/clouded-lock.png"),
  locked: require("../assets/images/locked.png"),
  rectangle: require("../assets/images/rectangle.png"),
  nike: require("../assets/images/nike.png"),
  neck: require("../assets/images/neck.png"),
  shirt: require("../assets/images/sweatshirt.png"),
  skincare: require("../assets/images/skincare.png"),
  gadgets: require("../assets/images/gadgets.png"),
  fashion: require("../assets/images/fashion.png"),
  appliances: require("../assets/images/appliances.png"),
  health: require("../assets/images/health.png"),
  homeandoffice: require("../assets/images/homeandoffice.png"),
  sneakers: require("../assets/images/sneakers.png"),
  heelz: require("../assets/images/heelz.png"),
  chopper: require("../assets/images/chopper.png"),
  icon: require("../assets/images/icon.png"),
  frame: require("../assets/images/frame.png"),
  cons: require("../assets/images/cons.png"),
  vendorone: require("../assets/images/vendorone.png"),
  vendortwo: require("../assets/images/vendortwo.png"),
};

export const carouselImages = [
  require("../assets/images/banner.png"),
  require("../assets/images/one.png"),
  require("../assets/images/two.png"),
  require("../assets/images/three.png"),
  require("../assets/images/five.png"),
];
